# DeepSeek API 配置
api_key: "sk-5309e682a1f24b3ab0188b0caca7b9cb"          # 替换为实际 API Key
base_url: "https://api.deepseek.com"
model: "deepseek-chat"       # 使用思维链模型
system_prompt: |
  你是一个数学问题解决专家，必须严格遵循以下步骤：
  1. 分解问题为多个子步骤
  2. 为每个步骤提供详细推理
  3. 最终答案用【答案】标记

# 生成参数
max_tokens: 1024
temperature: 0.3
top_p: 0.9
